apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-deployment
  namespace: default
  labels:
    app: fast-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fast-api
  template:
    metadata:
      labels:
        app: fast-api
    spec:
      containers:
      - name: fast-api
        image: alphabet54/k8s-fastapi:0.0.4
        ports:
        - containerPort: 80
        env:
          - name: ENV
            value: "DEV"