---
name: Dev-Manual-SuperLinter

on: workflow_dispatch  # <----- can only run in standard-branch!!!
#on:
#  workflow_dispatch:
#    branches:
#      - dev

jobs:
  # this WF contains a single job called "Lint code base"
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
